development:
  adapter: mysql2
  pool: 5
  encoding: utf8
  database: pagasalrecibir-dev
  username: ec2
  password: pagasalrecibir
  host: pagasalrecibir-dev.cjsjof8178js.us-east-1.rds.amazonaws.com
  port: 3306
  
